vim.keymap.set('n', '<leader>gcm', ':Git checkout master<CR>')
vim.keymap.set('n', '<leader>gp', ':Git pull<CR>')
vim.keymap.set('n', '<leader>gpm', ':Git pull origin master<CR>')
vim.keymap.set('n', '<leader>gpr', ':Git pull --rebase<CR>')
vim.keymap.set('n', '<leader>gP', ':Git push<CR>')
vim.keymap.set('n', '<leader>gs', ':Git stash<CR>')
vim.keymap.set('n', '<leader>gsp', ':Git stash pop<CR>')
