vim.keymap.set('n', '<leader>gg', ':Git<CR>', { desc = 'Open fugitive' })
vim.keymap.set('n', '<leader>gm', ':Git checkout master<CR>', { desc = 'Goto master' })
vim.keymap.set('n', '<leader>gp', ':Git pull<CR>', { desc = 'Pull' })
vim.keymap.set('n', '<leader>gu', ':Git pull origin master<CR>', { desc = 'Update master' })
vim.keymap.set('n', '<leader>gr', ':Git pull --rebase<CR>', { desc = 'Rebase' })
vim.keymap.set('n', '<leader>gP', ':Git push<CR>', { desc = 'Push' })
vim.keymap.set('n', '<leader>gs', ':Git stash<CR>', { desc = 'Stash' })
vim.keymap.set('n', '<leader>gS', ':Git stash pop<CR>', { desc = 'Stash pop' })
