set -g allow-passthrough on
set -s escape-time 0
set -g base-index 1

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

set -g status-style 'bg=black fg=white'

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

bind r source-file ~/.tmux.conf
