set -g base-index 1
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g bell-action none
setw -g monitor-activity off
set -as terminal-features ",st-256color:RGB"

# Copy mode
setw -g mode-style 'fg=red'

# Panes
set -g pane-border-style 'fg=magenta'
set -g pane-active-border-style 'fg=magenta'

# Statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'
set -g status-right ''

setw -g window-status-current-style 'fg=magenta bg=black'
setw -g window-status-current-format ' #I #[fg=green]#W #F '
setw -g window-status-style 'fg=magenta bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

# Messages
set -g message-style 'fg=yellow'

# Remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split panes using | and -
unbind '"'
unbind %
bind ) split-window -h
bind - split-window -v

# Reload the config
bind r source-file ~/.tmux.conf
