set -g base-index 1

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g bell-action none
setw -g monitor-activity off

# Status bar
set -g status on
set -g status-position top
set -g status-right ""
set -g status-style "bg=#2a283e fg=#e0def4"

# Pane styling
set -g pane-border-style "fg=#56526e"
set -g pane-active-border-style "fg=#ea9a97"
set -g display-panes-active-colour "#e0def4"
set -g display-panes-colour "#ea9a97"

# Windows
setw -g window-status-style "fg=#e0def4"
setw -g window-status-activity-style "fg=#232136"
setw -g window-status-current-style "fg=#c4a7e7"

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
unbind '"'
unbind %
bind ) split-window -h
bind - split-window -v

bind r source-file ~/.tmux.conf
